trigger: 
-master
pool:
vmImage : "ubuntu-latest"

steps:
-script: echo hello, world!
displayName: 'Run a one-line Script'

-script: echo Add a multiline script 
         echo one more
displayName: 'Run a multiline script'